### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by rusu24edward** [elgohr/Github-Release-Action#18]
I think I have not set something up correctly because I'm getting an unauthorized error.

This is my `release.yml` file:
```yaml
name: Publish Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: MyReleaseMessage
```
and I get this error:
```
/usr/bin/docker run --name a33c1cd19ccebbd934c2ab4024de496df75fa_04351d --label 8a33c1
--workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_ARGS -e INPUT_RELEASE -e HOME
-e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER
-e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR
-e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME
-e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE
-e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF
-e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP
-e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL
-e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock"
-v "/home/runner/work/_temp/_github_home":"/github/home"
-v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
-v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands"
-v "/home/runner/work/PyDV/PyDV":"/github/workspace" 8a33c1:cd19ccebbd934c2ab4024de496df75fa MyReleaseMessage
Error creating release: Unauthorized (HTTP 401)
Bad credentials
github.com username: github.com password for  (never stored): 
```

I'm new with using github actions and would greatly appreciate any direction.
