### ISSUE TITLE
How Can I have name of tag for args?

### ISSUE THREAD

**Issue by ragnarov** [elgohr/Github-Release-Action#28]
```
name: Publish Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: MyReleaseMessage
```
Say the name of the tag is `v0.001`
I want that to be `args`
How to do that?
It seems Environment variables can't be used
