### ISSUE TITLE
hub: not found - exit code 127

### ISSUE THREAD

**Issue by toschder** [elgohr/Github-Release-Action#49]
Hi
I tried this action in my workflow this way:
```
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: "v/${{ steps.release.outputs.version }}"
```
When running it fails with 
```
Run $GITHUB_ACTION_PATH/entrypoint.sh
  $GITHUB_ACTION_PATH/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CINEXT_PIPELINE: MajorRelease
    JAVA_HOME: /home/runner/actions-runner/_work/_tool/Java_Zulu_jdk/11.0.20-8/x64
    JAVA_HOME_11_X64: /home/runner/actions-runner/_work/_tool/Java_Zulu_jdk/11.0.20-8/x64
    GITHUB_TOKEN: 
    INPUT_TITLE: v/23.5.1
/home/runner/actions-runner/_work/_actions/elgohr/Github-Release-Action/v4/entrypoint.sh: 2: hub: not found
Error: Process completed with exit code 127.
```
Do I miss something or how can this be fixed ?
