### ISSUE TITLE
help: failed to run git: fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by alanwilter** [elgohr/Github-Release-Action#51]
I'm just trying to replace: deprecated `uses: actions/create-release@v1` with yours.

The relevant part:
```yml
  release:
    needs: check-test
    runs-on: ubuntu-20.04
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%-m.%-d')" >> $GITHUB_OUTPUT
        # run: echo "::set-output name=date::$(date +'%Y.%-m.%-d')"

      - name: Create tag
        # will only create a new release if the commit message is 'new_release' to master branch
        if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'new_tag')
        uses: actions/github-script@main
        with:
          # github-token: ${{ github.token }} # optional
          script: |
            github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.date.outputs.date }}",
            sha: context.sha
            })

      - name: Create Release
        # will only create a new release if the commit message is 'new_release' to master branch
        if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'new_release')
        id: create_release
        # uses: elgohr/Github-Release-Action@main
        uses: actions/create-release@main
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # title: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
```
The commented lines are the one that still works but when I try `Github-Release-Action` I get this error:
<img width="886" alt="Screenshot 2023-10-24 at 19 51 11" src="https://github.com/elgohr/Github-Release-Action/assets/3899850/c0a6dd4e-72de-4c71-8e92-b6553a31b0c9">
